from base.com.controller import area_controller
from base.com.controller import category_controller
from base.com.controller import city_controller
from base.com.controller import login_controller
from base.com.controller import state_controller
from base.com.controller import subcategory_controller
from base.com.controller import register_controller
from base.com.controller import complaint_feedback_controller
from base.com.controller import profile_controller
from base.com.controller import product_controller
from base.com.controller import test_contorller
